### ISSUE TITLE
Question about the normal UVmap?

### ISSUE THREAD

**Issue by utc1205** [barisgecer/TBGAN#1]
Hi, I have a question about normal UVmap after reading your paper. The vertices of face can obtain directly from shape UVmap, so the normal UVmap is for recalculating the vertice coordinates to improve the face mesh precision or it is only used to render face obj?

**Comment by barisgecer** [comment]
Hi, it is only used for rendering in our results but there are certain algorithms that recalculate shape from normals, so one can also use such.
