### ISSUE TITLE
Question about the outputs of the pre-trained model

### ISSUE THREAD

**Issue by atasoyfurkan** [barisgecer/TBGAN#10]
Hello, thanks for your work!

I have a question about the outputs of the pre-trained model. We acquired the pre-trained model from this [link](https://ibug.doc.ic.ac.uk/resources/tbgan/). However, our outputs are not the same as those presented in the paper. Unlike the presented results, our results don't generate neck parts of the 3D faces. 

Is there any additional processing part to add neck parts to our results?

I am attaching one of our results and a result from the paper.
<img width="250" alt="output" src="https://user-images.githubusercontent.com/46852761/172011978-69e4ca09-1951-4de6-9e40-5953a8e52ff3.png">
<img width="250" alt="paper-result" src="https://user-images.githubusercontent.com/46852761/172012209-ab95ae9c-254a-43e2-a3ab-44bd5f81ed16.png">

Thank you.

**Comment by barisgecer** [comment]
Hi Furkan,

There are two datasets and two pretrained models that are used in the paper (one with expression variation, and the other without). Unfortunately, only one of them is allowed to be public by their licenses (the one with expression). And the public one (the one you received) has a different topology that does not consist of the neck.

One quick solution you can apply if you really need neck and ears, you can fit Basel Face Model to any generated face and slowly interpolate from one to another.

Hope this helps,
Baris
