### ISSUE TITLE
Code availability update

### ISSUE THREAD

**Issue by super3kl** [barisgecer/TBGAN#2]
Hi! I would love to try this out， When do you target releasing the code?

**Comment by barisgecer** [comment]
In a month

**Comment by ghost** [comment]
@barisgecer will the pretrained models be released?

**Comment by barisgecer** [comment]
Hopefully yes. I am trying to set up a licensing agreement.

**Comment by renmengyuan** [comment]
Hi! And how about the dataset! @barisgecer

**Comment by barisgecer** [comment]
Unfortunately, the dataset is under a license and won't be released here.

**Comment by hadipash** [comment]
@barisgecer Any updates on publishing the pretrained model?

**Comment by barisgecer** [comment]
It is now available!

**Comment by Young1403** [comment]
@barisgecer 
Can ordinary students apply for the  pretrained model?

**Comment by barisgecer** [comment]
@Young1403 Unfortunately, it must be applied by a faculty member of an academic institution.
