### ISSUE TITLE
Questions about the detail normal map

### ISSUE THREAD

**Issue by ChangY-7** [barisgecer/TBGAN#3]
Hi, thanks for your great job! 

However, I am a little confused about the identity-generic maps. As mentioned in the paper, the detailed normal map for skin pores, one of the generic maps, should be added on the identity-specific map for improved rendering. How can we get this detailed normal map? Is there any ground truth for the skin pores?

Looking forward for your reply, thanks a lot!

**Comment by barisgecer** [comment]
@lattas

**Comment by lattas** [comment]
Hi @ChangY-7 , 

**How can we get this detailed normal map?**
Most of the identity-generic maps are created based on our training data and span the whole facial UV map. The detail normal map, is a patch of skin-pores that is tilled (repeated) accros the facial UV map. We have picked such a tile that resembles the average in our data. 

**Is there any ground truth for the skin pores?**
If you do not have ground truth data for skin pores, a quick search on "detail normal map" yields some ground truth examples and tutorials for synthetic data.

**...added on the identity-specific map for improved rendering**
Note that we don't literally add it on the identity specific map, but rather use it in a renderer that supports mid-frequency (generated identity specific)and high-frequency (identity generic) normal maps.

**Comment by ChangY-7** [comment]
> Hi @ChangY-7 ,
> 
> **How can we get this detailed normal map?**
> Most of the identity-generic maps are created based on our training data and span the whole facial UV map. The detail normal map, is a patch of skin-pores that is tilled (repeated) accros the facial UV map. We have picked such a tile that resembles the average in our data.
> 
> **Is there any ground truth for the skin pores?**
> If you do not have ground truth data for skin pores, a quick search on "detail normal map" yields some ground truth examples and tutorials for synthetic data.
> 
> **...added on the identity-specific map for improved rendering**
> Note that we don't literally add it on the identity specific map, but rather use it in a renderer that supports mid-frequency (generated identity specific)and high-frequency (identity generic) normal maps.

oh, I see. Thank you again for your detailed reply! (^_^)
