### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by flynnamy** [barisgecer/TBGAN#6]
Hi，when I run python test.py, it has problem like following picture. How to solve this? @barisgecer 
![image](https://user-images.githubusercontent.com/20398890/126783552-d9c3b587-4ab4-44cf-a60b-22caa319df1a.png)

**Comment by Prometheus1995** [comment]
Hello, i experienced the same Error Message. If anyone finds a solution i would be grateful :D

**Comment by Prometheus1995** [comment]
So i tried out different methods. I can create the tf-records for the mnist dataset but running them with train.py will fail with the same statement. I tried running it on google colab with gpu support maybe TBGAN is having trouble with that.

**Comment by Prometheus1995** [comment]
So im not 100% sure if those two are connected but calling util_scripts.generate_interpolation_images as a func seems to throw some errors in colab
![TBGANErroronFunc](https://user-images.githubusercontent.com/40771116/128080089-f9b4a70e-c8d3-4c42-ad3c-dc820fa4d51d.png)

**Comment by Prometheus1995** [comment]
So after some more tryouts i get this Error executing the test.py with the Model 
![TBGANErroronFunc](https://user-images.githubusercontent.com/40771116/128080977-2b3ffe01-81e1-43bc-8440-debf7bf186d1.png)

**Comment by barisgecer** [comment]
Hi guys,
The first error seems to be weird. tfutil.py has only comment line at line 236: https://github.com/barisgecer/TBGAN/blob/6c7134e86291d456b09ce728deac7ab265d178a7/tfutil.py#L236

You could check if you have the generate_interpolation_images function in util_scripts.py.

Finally, please re-clone the whole repository from scratch. I have played with the branches lately that might have confused your local git. 

Hope that helps. Let me know.
Baris

**Comment by Prometheus1995** [comment]
Hello, i started from scratch in colab 5 days ago and redid the same 2 days ago nothing changed since then. Looked for the generate_interpolation_images function in util_scripts and i still wondered if it is some problem with the .mp4 in the image generation? But if its working for you it may be a problem with the python path finding. Gonna check that tomorrow :D and thanks for the help :)

**Comment by barisgecer** [comment]
Please ignore mp4 codes in generate_interpolation_images. They are inherited from generate_interpolation_video but they are not actually used. I believe it is regarding path finding because obviously, it cannot import generate_interpolation_images function.

Also, have you checked the requirements? The code is based on Progressive Growing GAN from NVIDIA, so you can check if you can successfully run their code first. https://github.com/tkarras/progressive_growing_of_gans

**Comment by flynnamy** [comment]
Hi,how to solve like this? @barisgecer 
![image](https://user-images.githubusercontent.com/20398890/129680638-ffca5c0b-5004-4867-a7c1-f212f0c4634c.png)

**Comment by barisgecer** [comment]
@flynnamy I couldn't reproduce it. Did you try running https://github.com/tkarras/progressive_growing_of_gans ? Our code is built based on Pro-GAN. If you can run it, you should be able to run ours as well.

**Comment by aashishrai3799** [comment]
Hi,
I'm facing the same issue. I'm able to run Pro-GAN successfully but can't find a solution to this problem.

**Comment by XuZhengzhuo** [comment]
I have the same problem ...

**Comment by aashishrai3799** [comment]
I was able to solve this issue by installing menpo3d (pip install menpo3d).

**Comment by XuZhengzhuo** [comment]
> I have the same problem ...

I directly replace the following code in test.py:

```python
    tfutil.call_func_by_name(**config_test.train)
```

as:

```python
    from util_scripts import generate_interpolation_images
    config_test.num_gpus = 1
    config_test.desc = 'interpolation-images-' + str(config_test.train.run_id)
    generate_interpolation_images(run_id=32, grid_size=[1,1], duration_sec=5.0, smoothing_sec=0.1)
```
and it reminds me to install `menpo3d`. Then it works.

**Comment by barisgecer** [comment]
Thanks @aashishrai3799 and @XuZhengzhuo for letting us know what was the issue. I didn't realize that I already have menpo3d and the error is not self-explanatory anyway. I am glad we finally have a solution, I will add this to the readme file. Thanks again.

**Comment by XuZhengzhuo** [comment]
> Thanks @aashishrai3799 and @XuZhengzhuo for letting us know what was the issue. I didn't realize that I already have menpo3d and the error is not self-explanatory anyway. I am glad we finally have a solution, I will add this to the readme file. Thanks again.

Hi, how can I generate a 3D shape from a signal image (not from a random latent code)？I mean is there something like a `projector.py` in stylegan to encode a image into a latent code in your repo? Many thanks!!!

**Comment by barisgecer** [comment]
Unfortunately, my method does not have this feature. Since it is based on ProGAN , it does not inherit features from StyleGAN. Nevertheless, I believe it is doable like done in GANFit.

**Comment by flynnamy** [comment]
> > I have the same problem ...
> 
> I directly replace the following code in test.py:
> 
> ```python
>     tfutil.call_func_by_name(**config_test.train)
> ```
> 
> as:
> 
> ```python
>     from util_scripts import generate_interpolation_images
>     config_test.num_gpus = 1
>     config_test.desc = 'interpolation-images-' + str(config_test.train.run_id)
>     generate_interpolation_images(run_id=32, grid_size=[1,1], duration_sec=5.0, smoothing_sec=0.1)
> ```
> 
> and it reminds me to install `menpo3d`. Then it works.

I modify like this,but it has error,how to solve like this? Thanks! @XuZhengzhuo 
![image](https://user-images.githubusercontent.com/20398890/139370187-fdd88e5a-da90-4dfe-b14b-95c918206fb5.png)

**Comment by XuZhengzhuo** [comment]
> > > I have the same problem ...
> > 
> > 
> > I directly replace the following code in test.py:
> > ```python
> >     tfutil.call_func_by_name(**config_test.train)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > as:
> > ```python
> >     from util_scripts import generate_interpolation_images
> >     config_test.num_gpus = 1
> >     config_test.desc = 'interpolation-images-' + str(config_test.train.run_id)
> >     generate_interpolation_images(run_id=32, grid_size=[1,1], duration_sec=5.0, smoothing_sec=0.1)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and it reminds me to install `menpo3d`. Then it works.
> 
> I modify like this,but it has error,how to solve like this? Thanks! @XuZhengzhuo ![image](https://user-images.githubusercontent.com/20398890/139370187-fdd88e5a-da90-4dfe-b14b-95c918206fb5.png)

You may need to email the authors first and sign an `End User License Agreement`. The authors will give you the pretrain result and place it into '/results' directory.
