### ISSUE TITLE
Request for the code to cylindrically unwrap the mean face

### ISSUE THREAD

**Issue by sujit-rai** [barisgecer/TBGAN#8]
Hello! Thanks for sharing the code and your work.

Can you please point out the code to cylindrically unwrap the mean face for creating a UV representation corresponding to a specific mesh topology.

Thanks!

**Comment by barisgecer** [comment]
I think that might be useful https://github.com/menpo/lsfm

**Comment by X-niper** [comment]
> 

https://github.com/X-niper/UV_Unwrap

I just wrote one for the same use.
